bot:
  name: ShoppitBot
  token: ${BOT_TOKEN}
  past-date-minutes: 15

server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/sn
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 5544676Hen
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:database-market-changelog.xml
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        order_updates: true
        batch_versioned_data: true
        jdbc:
          batch-size: 32
    open-in-view: false

  jackson:
    serialization:
      write_dates_as_timestamps: false

wildberries:
  token: ${KEY}